name: simpegem-2017

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - mkl
  - tarfile
  - h5py
  - pip:
    - geoana==0.0.5
    - pymatsolver==0.1.2
    - discretize==0.3.8
    - SimPEG==0.10.4
