name: simpegem-2017

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - mkl
  - h5py
  - pip:
    - geoana==0.0.5
    - pymatsolver==0.1.2
    - discretize==0.4.7
    - SimPEG==0.11.5
